name: tamed_json
description: A utility library for JSON parsing and factory support in Dart.
version: 0.1.0
homepage: https://github.com/romarionce/tamed_json
license: MIT
environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.20.0
